# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fd4960f7056b3b71ae1d70c1878581ec245fa10dd0178ddd13930e0c1d7147c677b542b63d81d3f9932eb12935f87c12dfb671bd7478946773eda8ef6551eca5

test:
  secret_key_base: 7b221f5e6f6a8195b6af121f8f806479ca6ae7d137acc0172799e08c647e25b53083b036f3923b251ae77094f255cacbf76223a802b585aa258c550c873974a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
